#importamos la imagen base con python
FROM python:3.12-slim

#Creamos carpeta de trabajo del contenedor
WORKDIR /app
#Copiamos los requirimientos del servidor
COPY requirements.txt . 
#el punto para decirle que queremos uno igual a un lado

#instalamos los requerimientos
RUN pip install --no-cache-dir -r requirements.txt

#copiar el de API
COPY ./app ./app

#exponer el puerto
EXPOSE 5000

#comando de ejecución FASTAPI
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]